# Generated by Django 3.0.8 on 2020-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
